#pragma once
#include <ossia/detail/instantiations.hpp>
#include <ossia/editor/value/bool.hpp>
#include <ossia/editor/value/char.hpp>
#include <ossia/editor/value/destination.hpp>
#include <ossia/editor/value/float.hpp>
#include <ossia/editor/value/impulse.hpp>
#include <ossia/editor/value/int.hpp>
#include <ossia/editor/value/string.hpp>
#include <ossia/editor/value/tuple.hpp>
#include <ossia/editor/value/vec.hpp>
