var dir_2ea6d7dc795b7362a6c5868fd159a714 =
[
    [ "ossia-max/src/assert.hpp", "ossia-max_2src_2assert_8hpp_source.html", null ],
    [ "ossia-max/src/attribute.hpp", "ossia-max_2src_2attribute_8hpp_source.html", null ],
    [ "ossia-max/src/client.hpp", "ossia-max_2src_2client_8hpp_source.html", null ],
    [ "ossia-max/src/device.hpp", "ossia-max_2src_2device_8hpp_source.html", null ],
    [ "ossia-max/src/device_base.hpp", "ossia-max_2src_2device__base_8hpp_source.html", null ],
    [ "equals.hpp", "equals_8hpp_source.html", null ],
    [ "ossia-max/src/explorer.hpp", "ossia-max_2src_2explorer_8hpp_source.html", null ],
    [ "fuzzysearch.hpp", "fuzzysearch_8hpp_source.html", null ],
    [ "ossia-max/src/logger.hpp", "ossia-max_2src_2logger_8hpp_source.html", null ],
    [ "matcher.hpp", "matcher_8hpp_source.html", null ],
    [ "ossia-max/src/model.hpp", "ossia-max_2src_2model_8hpp_source.html", null ],
    [ "monitor.hpp", "monitor_8hpp_source.html", null ],
    [ "ossia-max/src/node_base.hpp", "ossia-max_2src_2node__base_8hpp_source.html", null ],
    [ "ossia-max/src/object_base.hpp", "ossia-max_2src_2object__base_8hpp_source.html", null ],
    [ "ocue.hpp", "ocue_8hpp_source.html", null ],
    [ "ocue.utils.cpp", "ocue_8utils_8cpp_source.html", null ],
    [ "ossia-max.hpp", "ossia-max_8hpp_source.html", null ],
    [ "ossia_object.hpp", "ossia__object_8hpp_source.html", null ],
    [ "ossia-max/src/parameter.hpp", "ossia-max_2src_2parameter_8hpp_source.html", null ],
    [ "ossia-max/src/parameter_base.hpp", "ossia-max_2src_2parameter__base_8hpp_source.html", null ],
    [ "ossia-max/src/remote.hpp", "ossia-max_2src_2remote_8hpp_source.html", null ],
    [ "router.hpp", "router_8hpp_source.html", null ],
    [ "search.hpp", "search_8hpp_source.html", null ],
    [ "search_filter.hpp", "search__filter_8hpp_source.html", null ],
    [ "symbols.hpp", "symbols_8hpp_source.html", null ],
    [ "ossia-max/src/utils.hpp", "ossia-max_2src_2utils_8hpp_source.html", null ],
    [ "ossia-max/src/view.hpp", "ossia-max_2src_2view_8hpp_source.html", null ],
    [ "ossia-max/src/ZeroconfMinuitListener.hpp", "ossia-max_2src_2_zeroconf_minuit_listener_8hpp_source.html", null ],
    [ "ossia-max/src/ZeroconfOscqueryListener.hpp", "ossia-max_2src_2_zeroconf_oscquery_listener_8hpp_source.html", null ]
];