var hierarchy =
[
    [ "ossia::regex_path::any_node", "structossia_1_1regex__path_1_1any__node.html", null ],
    [ "ossia::regex_path::any_path", "structossia_1_1regex__path_1_1any__path.html", null ],
    [ "ossia::nodes::automation", "classossia_1_1nodes_1_1automation.html", null ],
    [ "ossia::bad_request_error", "structossia_1_1bad__request__error.html", null ],
    [ "ossia::callback_container< T >", "classossia_1_1callback__container.html", null ],
    [ "ossia::callback_container< ossia::value_callback >", "classossia_1_1callback__container.html", null ],
    [ "ossia::callback_container< value_callback >", "classossia_1_1callback__container.html", [
      [ "ossia::net::parameter_base", "classossia_1_1net_1_1parameter__base.html", [
        [ "ossia::net::generic_parameter", "classossia_1_1net_1_1generic__parameter.html", null ]
      ] ]
    ] ],
    [ "opp::callback_index", "structopp_1_1callback__index.html", null ],
    [ "ossia::connection_error", "structossia_1_1connection__error.html", null ],
    [ "Contains", "class_contains.html", null ],
    [ "ossia::context", "structossia_1_1context.html", null ],
    [ "ossia::curve_abstract", "classossia_1_1curve__abstract.html", [
      [ "ossia::curve< double, float >", "classossia_1_1curve.html", null ],
      [ "ossia::constant_curve", "classossia_1_1constant__curve.html", null ],
      [ "ossia::curve< X, Y >", "classossia_1_1curve.html", null ]
    ] ],
    [ "Destination", "class_destination.html", null ],
    [ "ossia::detail::destination_index_retriever", "structossia_1_1detail_1_1destination__index__retriever.html", null ],
    [ "ossia::net::device_base", "classossia_1_1net_1_1device__base.html", null ],
    [ "ossia::net::device_capabilities", "structossia_1_1net_1_1device__capabilities.html", null ],
    [ "ossia::domain", "structossia_1_1domain.html", null ],
    [ "ossia::detail::domain_max_visitor_helper< T >", "structossia_1_1detail_1_1domain__max__visitor__helper.html", null ],
    [ "ossia::detail::domain_min_visitor_helper< T >", "structossia_1_1detail_1_1domain__min__visitor__helper.html", null ],
    [ "ossia::oscquery::detail::domain_to_json", "structossia_1_1oscquery_1_1detail_1_1domain__to__json.html", null ],
    [ "ossia::domain_value_set_creation_visitor", "structossia_1_1domain__value__set__creation__visitor.html", null ],
    [ "ossia::enum_map< K, V, N >", "classossia_1_1enum__map.html", null ],
    [ "ossia::max_binding::equals", "structossia_1_1max__binding_1_1equals.html", null ],
    [ "ossia::execution_error", "structossia_1_1execution__error.html", null ],
    [ "ossia::expressions::expression_atom", "classossia_1_1expressions_1_1expression__atom.html", null ],
    [ "ossia::expressions::expression_bool", "classossia_1_1expressions_1_1expression__bool.html", null ],
    [ "ossia::expressions::expression_composition", "classossia_1_1expressions_1_1expression__composition.html", null ],
    [ "ossia::expressions::expression_generic_base", "structossia_1_1expressions_1_1expression__generic__base.html", null ],
    [ "ossia::expressions::expression_not", "classossia_1_1expressions_1_1expression__not.html", null ],
    [ "ossia::expressions::expression_pulse", "classossia_1_1expressions_1_1expression__pulse.html", null ],
    [ "ossia::flat_set_state", "classossia_1_1flat__set__state.html", null ],
    [ "ossia::net::full_parameter_data", "structossia_1_1net_1_1full__parameter__data.html", null ],
    [ "ossia::generic_clamp", "structossia_1_1generic__clamp.html", null ],
    [ "ossia::oscquery::get_query_answerer", "classossia_1_1oscquery_1_1get__query__answerer.html", null ],
    [ "ossia::oscquery::host_info", "structossia_1_1oscquery_1_1host__info.html", null ],
    [ "Impulse", "class_impulse.html", null ],
    [ "opp::value::impulse", "structopp_1_1value_1_1impulse.html", null ],
    [ "ossia::net::instance_bounds", "structossia_1_1net_1_1instance__bounds.html", null ],
    [ "ossia::invalid_access_error", "structossia_1_1invalid__access__error.html", null ],
    [ "ossia::invalid_node_error", "structossia_1_1invalid__node__error.html", null ],
    [ "ossia::invalid_value_type_error", "structossia_1_1invalid__value__type__error.html", null ],
    [ "ossia::oscquery::json_parser", "structossia_1_1oscquery_1_1json__parser.html", null ],
    [ "ossia::oscquery::json_query_answerer", "structossia_1_1oscquery_1_1json__query__answerer.html", null ],
    [ "ossia::oscquery::json_writer", "classossia_1_1oscquery_1_1json__writer.html", null ],
    [ "ossia::oscquery::detail::json_writer_impl", "structossia_1_1oscquery_1_1detail_1_1json__writer__impl.html", null ],
    [ "ossia::list_clamp", "structossia_1_1list__clamp.html", null ],
    [ "osc::listener< MessageHandler >", "classosc_1_1listener.html", null ],
    [ "ossia::locked_container< Container >", "classossia_1_1locked__container.html", null ],
    [ "ossia::qt::log_sink", "classossia_1_1qt_1_1log__sink.html", null ],
    [ "ossia::nodes::mapping", "classossia_1_1nodes_1_1mapping.html", null ],
    [ "ossia::merger_impl", "structossia_1_1merger__impl.html", null ],
    [ "ossia::message", "structossia_1_1message.html", null ],
    [ "ossia::net::network_logger", "classossia_1_1net_1_1network__logger.html", null ],
    [ "opp::node", "classopp_1_1node.html", null ],
    [ "ossia::net::node_base", "classossia_1_1net_1_1node__base.html", null ],
    [ "ossia::node_not_found_error", "structossia_1_1node__not__found__error.html", null ],
    [ "ossia::oscquery::osc_type_visitor", "structossia_1_1oscquery_1_1osc__type__visitor.html", null ],
    [ "opp::oscquery_mirror", "classopp_1_1oscquery__mirror.html", null ],
    [ "opp::oscquery_server", "classopp_1_1oscquery__server.html", null ],
    [ "ossia::pair< T1, T2 >", "structossia_1_1pair.html", null ],
    [ "ossia::net::parameter_data", "structossia_1_1net_1_1parameter__data.html", null ],
    [ "ossia::parse_error", "structossia_1_1parse__error.html", null ],
    [ "ossia::regex_path::path_element", "structossia_1_1regex__path_1_1path__element.html", [
      [ "ossia::regex_path::any_between", "structossia_1_1regex__path_1_1any__between.html", null ],
      [ "ossia::regex_path::any_instance", "structossia_1_1regex__path_1_1any__instance.html", null ],
      [ "ossia::regex_path::device", "structossia_1_1regex__path_1_1device.html", null ]
    ] ],
    [ "ossia::net::protocol_base", "classossia_1_1net_1_1protocol__base.html", [
      [ "ossia::net::multiplex_protocol", "classossia_1_1net_1_1multiplex__protocol.html", null ],
      [ "ossia::oscquery::oscquery_server_protocol", "classossia_1_1oscquery_1_1oscquery__server__protocol.html", null ],
      [ "ossia::oscquery_asio::oscquery_server_protocol_base", "classossia_1_1oscquery__asio_1_1oscquery__server__protocol__base.html", null ]
    ] ],
    [ "ossia::oscquery::query_parser", "classossia_1_1oscquery_1_1query__parser.html", null ],
    [ "ossia::recabler", "structossia_1_1recabler.html", null ],
    [ "osc::receiver", "classosc_1_1receiver.html", null ],
    [ "osc::sender< ValueWriter >", "classosc_1_1sender.html", null ],
    [ "ossia::state", "classossia_1_1state.html", null ],
    [ "ossia::regex_path::stop", "structossia_1_1regex__path_1_1stop.html", null ],
    [ "ossia::time_event", "classossia_1_1time__event.html", null ],
    [ "ossia::time_interval", "classossia_1_1time__interval.html", null ],
    [ "ossia::time_process", "classossia_1_1time__process.html", null ],
    [ "ossia::time_sync", "classossia_1_1time__sync.html", null ],
    [ "ossia::time_value", "structossia_1_1time__value.html", null ],
    [ "tsBSpline", "structts_b_spline.html", null ],
    [ "tsBSplineImpl", "structts_b_spline_impl.html", null ],
    [ "tsDeBoorNet", "structts_de_boor_net.html", null ],
    [ "tsDeBoorNetImpl", "structts_de_boor_net_impl.html", null ],
    [ "tsFrame", "structts_frame.html", null ],
    [ "tsStatus", "structts_status.html", null ],
    [ "ossia::unit_t", "structossia_1_1unit__t.html", null ],
    [ "opp::value", "classopp_1_1value.html", null ],
    [ "ossia::value", "classossia_1_1value.html", null ],
    [ "ossia::value_with_unit", "structossia_1_1value__with__unit.html", null ],
    [ "opp::value::vec2f", "structopp_1_1value_1_1vec2f.html", null ],
    [ "opp::value::vec3f", "structopp_1_1value_1_1vec3f.html", null ],
    [ "opp::value::vec4f", "structopp_1_1value_1_1vec4f.html", null ],
    [ "ossia::net::websocket_client", "classossia_1_1net_1_1websocket__client.html", null ],
    [ "ossia::websocket_heartbeat", "structossia_1_1websocket__heartbeat.html", null ],
    [ "ossia::websocket_log_sink", "structossia_1_1websocket__log__sink.html", null ],
    [ "ossia::net::websocket_server", "classossia_1_1net_1_1websocket__server.html", null ]
];