var annotated =
[
    [ "OSSIA", null, [
      [ "Automation", "class_o_s_s_i_a_1_1_automation.html", "class_o_s_s_i_a_1_1_automation" ],
      [ "Clock", "class_o_s_s_i_a_1_1_clock.html", "class_o_s_s_i_a_1_1_clock" ],
      [ "CurveAbstract", "class_o_s_s_i_a_1_1_curve_abstract.html", "class_o_s_s_i_a_1_1_curve_abstract" ],
      [ "CurveSegment", "class_o_s_s_i_a_1_1_curve_segment.html", "class_o_s_s_i_a_1_1_curve_segment" ],
      [ "Curve", "class_o_s_s_i_a_1_1_curve.html", "class_o_s_s_i_a_1_1_curve" ],
      [ "Behavior", "struct_o_s_s_i_a_1_1_behavior.html", "struct_o_s_s_i_a_1_1_behavior" ],
      [ "CurveSegmentLinear", "class_o_s_s_i_a_1_1_curve_segment_linear.html", "class_o_s_s_i_a_1_1_curve_segment_linear" ],
      [ "CurveSegmentPower", "class_o_s_s_i_a_1_1_curve_segment_power.html", "class_o_s_s_i_a_1_1_curve_segment_power" ],
      [ "Domain", "class_o_s_s_i_a_1_1_domain.html", "class_o_s_s_i_a_1_1_domain" ],
      [ "Expression", "class_o_s_s_i_a_1_1_expression.html", "class_o_s_s_i_a_1_1_expression" ],
      [ "ExpressionAtom", "class_o_s_s_i_a_1_1_expression_atom.html", "class_o_s_s_i_a_1_1_expression_atom" ],
      [ "ExpressionComposition", "class_o_s_s_i_a_1_1_expression_composition.html", "class_o_s_s_i_a_1_1_expression_composition" ],
      [ "ExpressionNot", "class_o_s_s_i_a_1_1_expression_not.html", "class_o_s_s_i_a_1_1_expression_not" ],
      [ "Message", "class_o_s_s_i_a_1_1_message.html", "class_o_s_s_i_a_1_1_message" ],
      [ "Scenario", "class_o_s_s_i_a_1_1_scenario.html", "class_o_s_s_i_a_1_1_scenario" ],
      [ "State", "class_o_s_s_i_a_1_1_state.html", "class_o_s_s_i_a_1_1_state" ],
      [ "StateElement", "class_o_s_s_i_a_1_1_state_element.html", "class_o_s_s_i_a_1_1_state_element" ],
      [ "TimeConstraint", "class_o_s_s_i_a_1_1_time_constraint.html", "class_o_s_s_i_a_1_1_time_constraint" ],
      [ "TimeEvent", "class_o_s_s_i_a_1_1_time_event.html", "class_o_s_s_i_a_1_1_time_event" ],
      [ "TimeNode", "class_o_s_s_i_a_1_1_time_node.html", "class_o_s_s_i_a_1_1_time_node" ],
      [ "TimeProcess", "class_o_s_s_i_a_1_1_time_process.html", "class_o_s_s_i_a_1_1_time_process" ],
      [ "TimeValue", "class_o_s_s_i_a_1_1_time_value.html", "class_o_s_s_i_a_1_1_time_value" ],
      [ "Value", "class_o_s_s_i_a_1_1_value.html", "class_o_s_s_i_a_1_1_value" ],
      [ "Impulse", "struct_o_s_s_i_a_1_1_impulse.html", "struct_o_s_s_i_a_1_1_impulse" ],
      [ "Bool", "struct_o_s_s_i_a_1_1_bool.html", "struct_o_s_s_i_a_1_1_bool" ],
      [ "Int", "struct_o_s_s_i_a_1_1_int.html", "struct_o_s_s_i_a_1_1_int" ],
      [ "Float", "struct_o_s_s_i_a_1_1_float.html", "struct_o_s_s_i_a_1_1_float" ],
      [ "Char", "struct_o_s_s_i_a_1_1_char.html", "struct_o_s_s_i_a_1_1_char" ],
      [ "String", "struct_o_s_s_i_a_1_1_string.html", "struct_o_s_s_i_a_1_1_string" ],
      [ "Tuple", "struct_o_s_s_i_a_1_1_tuple.html", "struct_o_s_s_i_a_1_1_tuple" ],
      [ "Generic", "struct_o_s_s_i_a_1_1_generic.html", "struct_o_s_s_i_a_1_1_generic" ],
      [ "Address", "class_o_s_s_i_a_1_1_address.html", "class_o_s_s_i_a_1_1_address" ],
      [ "Device", "class_o_s_s_i_a_1_1_device.html", "class_o_s_s_i_a_1_1_device" ],
      [ "Node", "class_o_s_s_i_a_1_1_node.html", "class_o_s_s_i_a_1_1_node" ],
      [ "Destination", "struct_o_s_s_i_a_1_1_destination.html", "struct_o_s_s_i_a_1_1_destination" ],
      [ "Protocol", "class_o_s_s_i_a_1_1_protocol.html", "class_o_s_s_i_a_1_1_protocol" ],
      [ "Local", "struct_o_s_s_i_a_1_1_local.html", null ],
      [ "Minuit", "struct_o_s_s_i_a_1_1_minuit.html", "struct_o_s_s_i_a_1_1_minuit" ],
      [ "OSC", "struct_o_s_s_i_a_1_1_o_s_c.html", "struct_o_s_s_i_a_1_1_o_s_c" ],
      [ "Midi", "struct_o_s_s_i_a_1_1_midi.html", null ]
    ] ]
];